import { Inter } from 'next/font/google';
import '@/styles/globals.scss';
// 해당 경로는 jsconfig.json 파일에 설정되어있음
import Header from '@/components/header/Header';
import { GlobalProvider } from '@/hooks/useGlobalData';
import MobileMenu from '@/components/mobileMenu/MobileMenu';
import '@uploadthing/react/styles.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<GlobalProvider>
					<main className='container'>
						<Header />
						<div className='wrap'>{children}</div>
					</main>
					<MobileMenu />
				</GlobalProvider>
			</body>
		</html>
	);
}

/*
	app > layout.jsx : 메인페이지 전용 레이아웃 호출
	app폴더 안쪽의 모든 컴포넌트 파일은 기본적으로 ssr방식으로 동작하는 페이지 
	해당 페이지 컴포넌트에저 전역 style.scss연결 및 전역 state연결하는 GlobalProvider wrapping처리
*/
